# Generated by Django 3.1 on 2021-01-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210110_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='c_ans',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='d_ans',
            field=models.CharField(default='', max_length=500),
        ),
    ]
