# Generated by Django 3.1 on 2021-01-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20210110_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.category')),
            ],
        ),
    ]
