# Generated by Django 3.1 on 2021-01-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_ques_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_exam',
            name='ques_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
    ]
